### ISSUE TITLE
Dataframes with datetime indexes and timezone can be written but not read - TypeError: data type not understood

### ISSUE THREAD

**Issue by LorisMarini** [dask/fastparquet#433]
## Description
This bug concerns pandas dataframes which contain Datetime data with timezone information. When such data is part of a dataframe column, both writing and reading to/from a parquet file succeed. When the same data is part of the frame index, writing succeeds but reading fails. Note that if the datetime array is timezone insensitive (e.g. pd.date_range(start="2019-01-01", end="2019-05-01", freq="M", tz=None)), everything works fine. 

## Packages versions
pandas=0.24.2
fastparquet=0.3.1 (conda-forge)

## How to reproduce the error

\# Prepare dataframe
data_array = np.empty((4,3))
data_array[:] = np.nan
index = pd.DatetimeIndex(pd.date_range(start="2019-01-01", end="2019-05-01", freq="M", tz="UTC"))                       
df = pd.DataFrame(index=index, data=data_array, columns=["A", "B", "C"])

\# Move Datetime data to the columns
A = df.reset_index()

\# Keep Datetime on the index
B = df

\# Save and read back A
path="/tmp/test_pkl_to_par.parquet"

\# Write and read back A (works fine)
A.to_parquet(path, engine="fastparquet", compression='snappy', file_scheme='simple')
_ = pd.read_parquet(path, engine='fastparquet', columns=None)
print("Save and read back A: SUCCESS.")

\# Write and read back B (Raises error)
B.to_parquet(path, engine="fastparquet", compression='snappy', file_scheme='simple')
_ = pd.read_parquet(path, engine='fastparquet', columns=None)

## Output 

```
Save and read back A: SUCCESS.

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-105-332bf3f633c3> in <module>()
     16 # Save and read back B
     17 B.to_parquet(path, engine="fastparquet", compression='snappy', file_scheme='simple')
---> 18 pd.read_parquet(path, engine='fastparquet', columns=None)

/opt/conda/envs/myenv/lib/python3.6/site-packages/pandas/io/parquet.py in read_parquet(path, engine, columns, **kwargs)
    280 
    281     impl = get_engine(engine)
--> 282     return impl.read(path, columns=columns, **kwargs)

/opt/conda/envs/myenv/lib/python3.6/site-packages/pandas/io/parquet.py in read(self, path, columns, **kwargs)
    209             parquet_file = self.api.ParquetFile(path)
    210 
--> 211         return parquet_file.to_pandas(columns=columns, **kwargs)
    212 
    213 

/opt/conda/envs/myenv/lib/python3.6/site-packages/fastparquet/api.py in to_pandas(self, columns, categories, filters, index)
    416             columns += [i for i in index if i not in columns]
    417         check_column_names(self.columns + list(self.cats), columns, categories)
--> 418         df, views = self.pre_allocate(size, columns, categories, index)
    419         start = 0
    420         if self.file_scheme == 'simple':

/opt/conda/envs/myenv/lib/python3.6/site-packages/fastparquet/api.py in pre_allocate(self, size, columns, categories, index)
    440         categories = self.check_categories(categories)
    441         return _pre_allocate(size, columns, categories, index, self.cats,
--> 442                              self._dtypes(categories), self.tz)
    443 
    444     @property

/opt/conda/envs/myenv/lib/python3.6/site-packages/fastparquet/api.py in _pre_allocate(size, columns, categories, index, cs, dt, tz)
    555     dtypes.extend(['category'] * len(cs))
    556     df, views = dataframe.empty(dtypes, size, cols=cols, index_names=index,
--> 557                                 index_types=index_types, cats=cats, timezones=tz)
    558     return df, views
    559 

/opt/conda/envs/myenv/lib/python3.6/site-packages/fastparquet/dataframe.py in empty(types, size, cats, cols, index_types, index_names, timezones)
    114             views[col+'-catdef'] = index._data
    115         else:
--> 116             d = np.empty(size, dtype=t)
    117             index = Index(d)
    118             views[col] = index.values

TypeError: data type not understood
```

**Comment by martindurant** [comment]
There was a similar issue not too long ago, which was fixed. I don't know if the index was treated as part of that fix. Can you try with fastparquet from master?

**Comment by otmezger** [comment]
I have the same issue, installed fastparquet from master and the problem is still there...

**Comment by martindurant** [comment]
Copying the solution for columns looks like this, would you mind trying?
```diff
--- a/fastparquet/dataframe.py
+++ b/fastparquet/dataframe.py
@@ -119,7 +119,17 @@ def empty(types, size, cats=None, cols=None, index_types=None, index_names=None,
             views[col] = vals
             views[col+'-catdef'] = index._data
         else:
+            if hasattr(t, 'base'):
+                # funky pandas not-dtype
+                t = t.base
             d = np.empty(size, dtype=t)
+            if d.dtype.kind == "M" and six.text_type(col) in timezones:
+                try:
+                    d = Series(d).dt.tz_localize(timezones[six.text_type(col)])
+                except:
+                    warnings.warn("Inferring time-zone from %s in column %s "
+                                  "failed, using time-zone-agnostic"
+                                  "" % (timezones[six.text_type(col)], col))
             index = Index(d)
             views[col] = index.values
     else:
```

**Comment by callumstew** [comment]
I was having the same issue, but the above fix works for me

**Comment by martindurant** [comment]
Thanks for the ping ,I forgot about this.
